function [  ] = genmfuninvdyn( CGen )
%GENMFUNFDYN Summary of this function goes here
%   Detailed explanation goes here

CGen.logmsg([datestr(now),'\tGenerating inverse dynamics m-function:']);

funfilename = fullfile(CGen.robjpath,'invdyn.m');
hStruct = createHeaderStruct(CGen.rob,funfilename);

fid = fopen(funfilename,'w+');

fprintf(fid, '%s\n', ['function tau = invdyn(rob,q,qd,qdd)']);                 % Function definition
fprintf(fid, '%s\n',constructheaderstring(CGen,hStruct));                   % Header

fprintf(fid, '%s \n', 'tau = zeros(length(q),1);');                        % Code

funcCall = ['tau = rob.inertia(q)*qdd.'' + ',...
    'rob.coriolis(q,qd)*qd.'' + ',...
    'rob.gravload(q) + ', ...
    'rob.friction(qd);'];
fprintf(fid, '%s \n', funcCall);


fclose(fid);

CGen.logmsg('\t%s\n',' done!');
end



%% Definition of the RST-header contents for each generated file
function hStruct = createHeaderStruct(rob,fName)
[~,hStruct.funName] = fileparts(fName);
hStruct.shortDescription = ['Inverse dynamics for the',rob.name,' arm.'];
hStruct.calls = {['tau = ',hStruct.funName,'(q,qDot,qDDot)']};
hStruct.detailedDescription = {'Given a full set of joint variables and their first and second order',...
    'time derivatives this function computes the joint space',...
    'torques needed to perform the particular motion.'};
hStruct.inputs = {['q:  ',int2str(rob.n),'-element vector of generalized joint coordinates.'],...
    ['qDot:  ',int2str(rob.n),'-element vector of generalized joint velocities.'],...
    ['qDDot:  ',int2str(rob.n),'-element vector of generalized joint accelerations.']};
hStruct.outputs = {['tau:  [',int2str(rob.n),'x1] vector of generalized joint forces.']};
hStruct.references = {'1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar',...
    '2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano',...
    '3) Introduction to Robotics, Mechanics and Control - Craig',...
    '4) Modeling, Identification & Control of Robots - Khalil & Dombre'};
hStruct.authors = {'This is an autogenerated function!',...
    'Generator createInvDynamicsDH written by:',...
    'Jörn Malzahn   '};
hStruct.seeAlso = {rob.name,'createInvDynamicsDH'};
end