function bfixString = getPiBugfixString(CGen)
%% GETPIBUGFIXSTRING Returns a string to fix PI-Bug in auto genereated functions.
% =========================================================================
% 
%   bfixString = getPiBugfixString()
% 
%  Description::
%    In some versions the symbolic toolbox writes the constant $pi$ in
%    capital letters. This way autogenerated functions might not work properly. 
%    To fix this issue a local variable is introduced:
%    PI = pi
%
%  Output::
%       bfixString: String with explanation comment and variable declaration.
% 
%  Authors::
%        Jörn Malzahn   
%        2012 RST, Technische Universität Dortmund, Germany
%        http://www.rst.e-technik.tu-dortmund.de   
% 
%  See also constructheaderstring, replaceheader.

bfixString = [];
bfixString = [bfixString, sprintf('%s\n','%% Bugfix')];
bfixString = [bfixString, sprintf('%s\n','%  In some versions the symbolic toolbox writes the constant $pi$ in')];
bfixString = [bfixString, sprintf('%s\n','%  capital letters. This way autogenerated functions might not work properly.')];
bfixString = [bfixString, sprintf('%s\n','%  To fix this issue a local variable is introduced:')];
bfixString = [bfixString, sprintf('%s\n','PI = pi;')];
bfixString = [bfixString, sprintf('%s\n','   ')];